[package]
name = "factotum"
version = "0.2.0"
authors = ["Ed Lewis <support@snowplowanalytics.com>"]

[dependencies]
docopt = "0.6"
log = "0.3.5"
log4rs = "0.3.3"
daggy = "0.4.0"
rustc-serialize = "0.3.18"
valico = "0.8.2"
chrono = "0.2"
colored = "1.2"
mustache = "*"